config/routes.rb
Loopapp::Application.routes.draw do
  get "home/index"
  resources :players do
    collection {post :import}
  end

  resources :facilities do
    collection {post :import}
  end

  resources :holes do
    collection {post :import}
  end

  resources :courses do
    collection {post :import}
  end

  resources :tees do
    collection {post :import}
  end 

  resources :rounds do
    collection {post :import}
  end

  resources :round_holes do
    collection {post :import}
  end

  resources :shots do
    collection {post :import}
  end

  resources :clubs do
    collection {post :import}
  end

  root 'home#index'

  

end

app/models/club.rb
class Club < ActiveRecord::Base
	has_many :shots
	belongs_to :player

	def self.import(file)
		CSV.foreach(file.path, headers: true) do |row|
			clubs = find_by_id(row["id"]) ||new
			clubs.attributes = row.to_hash.slice(*Club.attribute_names())
			clubs.save!
		end
	end
end

app/models/course.rb
class Course < ActiveRecord::Base
	belongs_to :facility
	has_many :rounds
	has_many :holes

	def self.import(file)
	CSV.foreach(file.path, headers: true) do |row|
		courses = find_by_id(row["id"]) ||new
		courses.attributes = row.to_hash.slice(*Course.attribute_names())
		courses.save!
		end
	end
end

app/models/facility.rb
class Facility < ActiveRecord::Base
	has_many :courses

	def self.import(file)
	CSV.foreach(file.path, headers: true) do |row|
		facilities = find_by_id(row["id"]) ||new
		facilities.attributes = row.to_hash.slice(*Facility.attribute_names())
		facilities.save!
		end
	end	
end

app/models/hole.rb
class Hole < ActiveRecord::Base
	belongs_to :course
	has_many :roundholes

	def self.import(file)
	CSV.foreach(file.path, headers: true) do |row|
		holes = find_by_id(row["id"]) ||new
		holes.attributes = row.to_hash.slice(*Hole.attribute_names())
		holes.save!
		end
	end	
end

app/models/player.rb
class Player < ActiveRecord::Base
	has_many :rounds
	has_many :clubs

	def self.import(file)
	CSV.foreach(file.path, headers: true) do |row|
		players = find_by_id(row["id"]) ||new
		players.attributes = row.to_hash.slice(*Player.attribute_names())
		players.save!
		end
	end	
end

app/models/round.rb
class Round < ActiveRecord::Base
	belongs_to :tee
	belongs_to :player
	belongs_to :course
	has_many :roundholes

	def self.import(file)
	CSV.foreach(file.path, headers: true) do |row|
		rounds = find_by_id(row["id"]) ||new
		rounds.attributes = row.to_hash.slice(*Round.attribute_names())
		rounds.save!
		end
	end	
end

app/models/round_hole.rb
class RoundHole < ActiveRecord::Base
	has_many :shots
	belongs_to :round 
	belongs_to :hole 

	def self.import(file)
	CSV.foreach(file.path, headers: true) do |row|
		roundholes = find_by_id(row["id"]) ||new
		roundholes.attributes = row.to_hash.slice(*RoundHole.attribute_names())
		roundholes.save!
		end
	end	
end

app/models/shot.rb
class Shot < ActiveRecord::Base
	belongs_to :club
	belongs_to :roundhole

	def self.import(file)
	CSV.foreach(file.path, headers: true) do |row|
		shots = find_by_id(row["id"]) ||new
		shots.attributes = row.to_hash.slice(*Shot.attribute_names())
		shots.save!
		end
	end	
end

app/models/tee.rb
class Tee < ActiveRecord::Base
	belongs_to :course
	has_many :rounds

	def self.import(file)
	CSV.foreach(file.path, headers: true) do |row|
		tees = find_by_id(row["id"]) ||new
		tees.attributes = row.to_hash.slice(*Tee.attribute_names())
		tees.save!
		end
	end	
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  before_action :set_club, only: [:show, :edit, :update, :destroy]
  protect_from_forgery with: :null_session #fixed "Can't verify CSRF token authenticity error, however not sure if this opens up security hole"
  respond_to :html, :json, :csv


  # GET /clubs
  # GET /clubs.json
  def index
    @clubs = Club.all
    respond_with @clubs, :include => :id
  end

  # GET /clubs/1
  # GET /clubs/1.json
  def show
    @club = Club.find(params[:id])
    respond_with @club, :include => :id
  end

  # GET /clubs/new
  def new
    @club = Club.new
  end

  # GET /clubs/1/edit
  def edit
    @club = Club.find(params[:id])
  end

  # POST /clubs
  # POST /clubs.json
  def create
    @club = Club.new(club_params)
    @club.save
    respond_with @club
  end

  # PATCH/PUT /clubs/1
  # PATCH/PUT /clubs/1.json
  def update
   @club = Club.find(params[:id])
   @club.update_attributes(club_params)
   respond_with @club
  end

  # DELETE /clubs/1
  # DELETE /clubs/1.json
  def destroy
    @club = Club.find(params[:id])
    @club.destroy
    respond_with @club
  end

    #Import CSV
    def import
      Club.import(params[:file])
      redirect_to root_url, alert: "Clubs Imported"
    end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_club
      @club = Club.find(params[:id])
    end

     # Never trust parameters from the scary internet, only allow the white list through.
    def club_params
      params.require(:club).permit(:player_id, :make, :model, :order, :name)
    end   
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/tees_controller.rb
class TeesController < ApplicationController
  before_action :set_tee, only: [:show, :edit, :update, :destroy]
  protect_from_forgery with: :null_session #fixed "Can't verify CSRF token authenticity error, however not sure if this opens up security hole"
  respond_to :html, :json, :csv

  # GET /tees
  # GET /tees.json
  def index
    @tees = Tee.all
    respond_with @tees
  end

  # GET /tees/1
  # GET /tees/1.json
  def show
    @tee = Tee.find(params[:id])
    respond_with @tee
  end

  # GET /tees/new
  def new
    @tee = Tee.new
  end

  # GET /tees/1/edit
  def edit
    @tee = Tee.find(params[:id])
  end

  # POST /tees
  # POST /tees.json
  def create
    @tee = Tee.new(tee_params)
    @tee.save
    respond_with @tee
  end

  # PATCH/PUT /tees/1
  # PATCH/PUT /tees/1.json
  def update
    @tee = Tee.find(params[:id])
    @tee.update_attributes(tee_params)
    respond_with @tee
  end

  # DELETE /tees/1
  # DELETE /tees/1.json
  def destroy
    @tee = Tee.find(params[:id])
    @tee.destroy
    respond_with @tee
  end

  #Import CSV
  def import
    Tee.import(params[:file])
    redirect_to root_url, alert: "Tees Imported"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tee
      @tee = Tee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tee_params
      params.require(:tee).permit(:course_id, :name, :distance, :courseRating, :slopeRating)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/facilities_helper.rb
module FacilitiesHelper
end

app/helpers/holes_helper.rb
module HolesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/round_holes_helper.rb
module RoundHolesHelper
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/helpers/shots_helper.rb
module ShotsHelper
end

app/helpers/tees_helper.rb
module TeesHelper
end

app/views/clubs/_form.html.erb
<%= form_for(@club) do |f| %>
  <% if @club.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@club.errors.count, "error") %> prohibited this club from being saved:</h2>

      <ul>
      <% @club.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="container">
  <div class="field">
    <%= f.label :player_id %><br>
    <%= f.number_field :player_id %>
  <div class="field">
    <%= f.label :make %><br>
    <%= f.text_field :make %>
  </div>
  <div class="field">
    <%= f.label :model %><br>
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :order %><br>
    <%= f.number_field :order %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.number_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  </div>
<% end %>

app/views/clubs/edit.html.erb
<h1>Editing Club</h1>

<%= render 'form' %>

<%= link_to 'Show', @club %> |
<%= link_to 'Back', clubs_path %>

app/views/clubs/index.csv.erb
<%=
response.content_type = 'application/clubs'
CSV.generate do |csv|
	csv << ["id", "player_id", "make", "model", "order", "name"]
	@clubs.each do |club|
    csv << [ club[:id], club[:player_id], club[:make], club[:model], club[:order], club[:name] ]
  end
end .html_safe
%>

app/views/clubs/index.html.erb
<div class="container">
<h1>All Clubs</h1>


<table class="table table-hover table-responsive table-bordered">
  <thead>
    <tr>
      <th>ID</th>
      <th>Player ID</th>
      <th>Make</th>
      <th>Model</th>
      <th>Order</th>
      <th>Name</th>
    </tr>
  </thead>

  <tbody>
    <% @clubs.each do |club| %>
      <tr>
        <td><%= club.id %></td>
        <td><%= club.player_id %></td>
        <td><%= club.make %></td>
        <td><%= club.model %></td>
        <td><%= club.order %></td>
        <td><%= club.name %></td>
        <td><%= link_to 'Show', club %></td>
        <td><%= link_to 'Edit', edit_club_path(club) %></td>
        <td><%= link_to 'Destroy', club, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Club', new_club_path, :class=>"btn btn-primary" %>
<%= link_to '.CSV', clubs_path(format: "csv") , :class=>"btn btn-primary" %>

<h2>Import Clubs</h2>

<%= form_tag import_clubs_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>
</div>

app/views/clubs/new.html.erb
<div class="container">
<h1>New Club</h1>

<%= render 'form' %>

<%= link_to 'Back', clubs_path %>
</div>

app/views/clubs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>ID:</strong>
  <%= @club.id %>
</p>

<p>
  <strong>Player ID:</strong>
  <%= @club.player_id %>
</p>

<p>
  <strong>Make:</strong>
  <%= @club.make %>
</p>

<p>
  <strong>Model:</strong>
  <%= @club.model %>
</p>

<p>
  <strong>Order:</strong>
  <%= @club.order %>
</p>

<p>
  <strong>Name:</strong>
  <%= @club.name %>
</p>

<%= link_to 'Edit', edit_club_path(@club) %> |
<%= link_to 'Back', clubs_path %>

app/views/tees/_form.html.erb
<%= form_for(@tee) do |f| %>
  <% if @tee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tee.errors.count, "error") %> prohibited this tee from being saved:</h2>

      <ul>
      <% @tee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :course_id %><br>
    <%= f.number_field :course_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.number_field :name %>
  </div>
  <div class="field">
    <%= f.label :distance %><br>
    <%= f.number_field :distance %>
  </div>
  <div class="field">
    <%= f.label :courseRating %><br>
    <%= f.text_field :courseRating %>
  </div>
  <div class="field">
    <%= f.label :slopeRating %><br>
    <%= f.number_field :slopeRating %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tees/edit.html.erb
<h1>Editing Tee</h1>

<%= render 'form' %>

<%= link_to 'Show', @tee %> |
<%= link_to 'Back', tees_path %>

app/views/tees/index.csv.erb
<%=
response.content_type = 'application/tees'
CSV.generate do |csv|
	csv << ["id", "course_id" "name", "distance", "courseRating", "slopeRating"]
	@tees.each do |tee|
    csv << [ tee[:id], tee[:course_id], tee[:name], tee[:distance], tee[:courseRating], tee[:slopeRating]]
  end
end .html_safe
%>

app/views/tees/index.html.erb
<div class="container">
<h1>All Tees</h1>

<table class="table table-hover table-responsive table-bordered">
  <thead>
    <tr>
      <th>ID</th>
      <th>Course ID</th>
      <th>Name</th>
      <th>Distance</th>
      <th>Course Rating</th>
      <th>Slope Rating</th>
    </tr>
  </thead>

  <tbody>
    <% @tees.each do |tee| %>
      <tr>
        <td><%= tee.id %></td>
        <td><%= tee.course_id %></td>
        <td><%= tee.name %></td>
        <td><%= tee.distance %></td>
        <td><%= tee.courseRating %></td>
        <td><%= tee.slopeRating %></td>
        <td><%= link_to 'Show', tee %></td>
        <td><%= link_to 'Edit', edit_tee_path(tee) %></td>
        <td><%= link_to 'Destroy', tee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tee', new_tee_path, :class=>"btn btn-primary" %>
<%= link_to '.CSV', tees_path(format: "csv") , :class=>"btn btn-primary" %>

<h2>Import Tees</h2>
<%= form_tag import_tees_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>
</div>

app/views/tees/new.html.erb
<h1>New Tee</h1>

<%= render 'form' %>

<%= link_to 'Back', tees_path %>

app/views/tees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>ID:</strong>
  <%= @tee.id %>
</p>

<p>
  <strong>Cours ID:</strong>
  <%= @tee.course_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @tee.name %>
</p>

<p>
  <strong>Distance:</strong>
  <%= @tee.distance %>
</p>

<p>
  <strong>Courserating:</strong>
  <%= @tee.courseRating %>
</p>

<p>
  <strong>Sloperating:</strong>
  <%= @tee.slopeRating %>
</p>

<%= link_to 'Edit', edit_tee_path(@tee) %> |
<%= link_to 'Back', tees_path %>