config/routes.rb
Loopapp::Application.routes.draw do
  get "home/index"
  resources :players do
    collection {post :import}
  end

  resources :facilities do
    collection {post :import}
  end

  resources :holes do
    collection {post :import}
  end

  resources :courses do
    collection {post :import}
  end

  resources :tees do
    collection {post :import}
  end 

  resources :rounds do
    collection {post :import}
  end

  resources :round_holes do
    collection {post :import}
  end

  resources :shots do
    collection {post :import}
  end

  resources :clubs do
    collection {post :import}
  end

  root 'home#index'

  

end

app/models/club.rb
class Club < ActiveRecord::Base
	has_many :shots
	belongs_to :player

	def self.import(file)
		CSV.foreach(file.path, headers: true) do |row|
			clubs = find_by_id(row["id"]) ||new
			clubs.attributes = row.to_hash.slice(*Club.attribute_names())
			clubs.save!
		end
	end
end

app/models/course.rb
class Course < ActiveRecord::Base
	belongs_to :facility
	has_many :rounds
	has_many :holes

	def self.import(file)
	CSV.foreach(file.path, headers: true) do |row|
		courses = find_by_id(row["id"]) ||new
		courses.attributes = row.to_hash.slice(*Course.attribute_names())
		courses.save!
		end
	end
end

app/models/facility.rb
class Facility < ActiveRecord::Base
	has_many :courses

	def self.import(file)
	CSV.foreach(file.path, headers: true) do |row|
		facilities = find_by_id(row["id"]) ||new
		facilities.attributes = row.to_hash.slice(*Facility.attribute_names())
		facilities.save!
		end
	end	
end

app/models/hole.rb
class Hole < ActiveRecord::Base
	belongs_to :course
	has_many :roundholes

	def self.import(file)
	CSV.foreach(file.path, headers: true) do |row|
		holes = find_by_id(row["id"]) ||new
		holes.attributes = row.to_hash.slice(*Hole.attribute_names())
		holes.save!
		end
	end	
end

app/models/player.rb
class Player < ActiveRecord::Base
	has_many :rounds
	has_many :clubs

	def self.import(file)
	CSV.foreach(file.path, headers: true) do |row|
		players = find_by_id(row["id"]) ||new
		players.attributes = row.to_hash.slice(*Player.attribute_names())
		players.save!
		end
	end	
end

app/models/round.rb
class Round < ActiveRecord::Base
	belongs_to :tee
	belongs_to :player
	belongs_to :course
	has_many :roundholes

	def self.import(file)
	CSV.foreach(file.path, headers: true) do |row|
		rounds = find_by_id(row["id"]) ||new
		rounds.attributes = row.to_hash.slice(*Round.attribute_names())
		rounds.save!
		end
	end	
end

app/models/round_hole.rb
class RoundHole < ActiveRecord::Base
	has_many :shots
	belongs_to :round 
	belongs_to :hole 

	def self.import(file)
	CSV.foreach(file.path, headers: true) do |row|
		roundholes = find_by_id(row["id"]) ||new
		roundholes.attributes = row.to_hash.slice(*RoundHole.attribute_names())
		roundholes.save!
		end
	end	
end

app/models/shot.rb
class Shot < ActiveRecord::Base
	belongs_to :club
	belongs_to :roundhole

	def self.import(file)
	CSV.foreach(file.path, headers: true) do |row|
		shots = find_by_id(row["id"]) ||new
		shots.attributes = row.to_hash.slice(*Shot.attribute_names())
		shots.save!
		end
	end	
end

app/models/tee.rb
class Tee < ActiveRecord::Base
	belongs_to :course
	has_many :rounds

	def self.import(file)
	CSV.foreach(file.path, headers: true) do |row|
		tees = find_by_id(row["id"]) ||new
		tees.attributes = row.to_hash.slice(*Tee.attribute_names())
		tees.save!
		end
	end	
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/round_holes_controller.rb
class RoundHolesController < ApplicationController
  before_action :set_round_hole, only: [:show, :edit, :update, :destroy]
  protect_from_forgery with: :null_session #fixed "Can't verify CSRF token authenticity error, however not sure if this opens up security hole"
  respond_to :html, :json, :csv

  # GET /round_holes
  # GET /round_holes.json
  def index
    @round_holes = RoundHole.all
    respond_with @round_holes
  end

  # GET /round_holes/1
  # GET /round_holes/1.json
  def show
    @round_hole = RoundHole.find(params[:id])
    respond_with @round_hole
  end

  # GET /round_holes/new
  def new
    @round_hole = RoundHole.new
  end

  # GET /round_holes/1/edit
  def edit
   @round_hole = RoundHole.find(params[:id])
  end

  # POST /round_holes
  # POST /round_holes.json
  def create
    @round_hole = RoundHole.new(round_hole_params)
    @round_hole.save
    respond_with @round_hole    
  end

  # PATCH/PUT /round_holes/1
  # PATCH/PUT /round_holes/1.json
  def update
    @round_hole = RoundHole.find(params[:id])
    @round_hole.update_attributes(round_hole_params)
    respond_with @round_hole
  end

  # DELETE /round_holes/1
  # DELETE /round_holes/1.json
  def destroy
    @round_hole = RoundHole.find(params[:id])
    @round_hole.destroy
    respond_with @round_hole    
  end

  #Import CSV
  def import
    RoundHole.import(params[:file])
    redirect_to root_url, alert: "Round Holes Imported"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_round_hole
      @round_hole = RoundHole.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def round_hole_params
      params.require(:round_hole).permit(:round_id, :hole_id)
    end
end

app/controllers/tees_controller.rb
class TeesController < ApplicationController
  before_action :set_tee, only: [:show, :edit, :update, :destroy]
  protect_from_forgery with: :null_session #fixed "Can't verify CSRF token authenticity error, however not sure if this opens up security hole"
  respond_to :html, :json, :csv

  # GET /tees
  # GET /tees.json
  def index
    @tees = Tee.all
    respond_with @tees
  end

  # GET /tees/1
  # GET /tees/1.json
  def show
    @tee = Tee.find(params[:id])
    respond_with @tee
  end

  # GET /tees/new
  def new
    @tee = Tee.new
  end

  # GET /tees/1/edit
  def edit
    @tee = Tee.find(params[:id])
  end

  # POST /tees
  # POST /tees.json
  def create
    @tee = Tee.new(tee_params)
    @tee.save
    respond_with @tee
  end

  # PATCH/PUT /tees/1
  # PATCH/PUT /tees/1.json
  def update
    @tee = Tee.find(params[:id])
    @tee.update_attributes(tee_params)
    respond_with @tee
  end

  # DELETE /tees/1
  # DELETE /tees/1.json
  def destroy
    @tee = Tee.find(params[:id])
    @tee.destroy
    respond_with @tee
  end

  #Import CSV
  def import
    Tee.import(params[:file])
    redirect_to root_url, alert: "Tees Imported"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tee
      @tee = Tee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tee_params
      params.require(:tee).permit(:course_id, :name, :distance, :courseRating, :slopeRating)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/facilities_helper.rb
module FacilitiesHelper
end

app/helpers/holes_helper.rb
module HolesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/round_holes_helper.rb
module RoundHolesHelper
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/helpers/shots_helper.rb
module ShotsHelper
end

app/helpers/tees_helper.rb
module TeesHelper
end

app/views/round_holes/_form.html.erb
<%= form_for(@round_hole) do |f| %>
  <% if @round_hole.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@round_hole.errors.count, "error") %> prohibited this round_hole from being saved:</h2>

      <ul>
      <% @round_hole.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :round_id %><br>
    <%= f.number_field :round_id %>
  </div>
    <div class="field">
    <%= f.label :hole_id %><br>
    <%= f.number_field :hole_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/round_holes/edit.html.erb
<h1>Editing Round Hole</h1>

<%= render 'form' %>

<%= link_to 'Show', @round_hole %> |
<%= link_to 'Back', round_holes_path %>

app/views/round_holes/index.csv.erb
<%=
response.content_type = 'application/round_holes'
CSV.generate do |csv|
	csv << ["id", "round_id", "hole_id"]
	@round_holes.each do |round_hole|
    csv << [ round_hole[:id], round_hole[:round_id], round_hole[:hole_id]]
  end
end .html_safe
%>

app/views/round_holes/index.html.erb
<div class="container">
<h1>All Round Holes</h1>

<table class="table table-hover table-responsive table-bordered">
  <thead>
    <tr>
      <th>ID</th>
      <th>Round ID</th>
      <th>Hole ID</th>
    </tr>
  </thead>

  <tbody>
    <% @round_holes.each do |round_hole| %>
      <tr>
        <td><%= round_hole.id %></td>
        <td><%= round_hole.round_id %></td>
        <td><%= round_hole.hole_id %></td>
        <td><%= link_to 'Show', round_hole %></td>
        <td><%= link_to 'Edit', edit_round_hole_path(round_hole) %></td>
        <td><%= link_to 'Destroy', round_hole, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Round hole', new_round_hole_path, :class=>"btn btn-primary" %>
<%= link_to '.CSV', round_holes_path(format: "csv") , :class=>"btn btn-primary" %>

<h2>Import Round Holes</h2>
<%= form_tag import_round_holes_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>
</div>

app/views/round_holes/new.html.erb
<h1>New Round Hole</h1>

<%= render 'form' %>

<%= link_to 'Back', round_holes_path %>

app/views/round_holes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>ID:</strong>
  <%= @round_hole.id %>
</p>

<p>
  <strong>Round ID:</strong>
  <%= @round_hole.round_id %>
</p>

<p>
  <strong>Hole ID:</strong>
  <%= @round_hole.hole_id %>
</p>

<%= link_to 'Edit', edit_round_hole_path(@round_hole) %> |
<%= link_to 'Back', round_holes_path %>