config/routes.rb
Loopapp::Application.routes.draw do
  get "home/index"
  resources :players do
    collection {post :import}
  end

  resources :facilities do
    collection {post :import}
  end

  resources :holes do
    collection {post :import}
  end

  resources :courses do
    collection {post :import}
  end

  resources :tees do
    collection {post :import}
  end 

  resources :rounds do
    collection {post :import}
  end

  resources :round_holes do
    collection {post :import}
  end

  resources :shots do
    collection {post :import}
  end

  resources :clubs do
    collection {post :import}
  end

  root 'home#index'

  

end

app/models/club.rb
class Club < ActiveRecord::Base
	has_many :shots
	belongs_to :player

	def self.import(file)
		CSV.foreach(file.path, headers: true) do |row|
			clubs = find_by_id(row["id"]) ||new
			clubs.attributes = row.to_hash.slice(*Club.attribute_names())
			clubs.save!
		end
	end
end

app/models/course.rb
class Course < ActiveRecord::Base
	belongs_to :facility
	has_many :rounds
	has_many :holes

	def self.import(file)
	CSV.foreach(file.path, headers: true) do |row|
		courses = find_by_id(row["id"]) ||new
		courses.attributes = row.to_hash.slice(*Course.attribute_names())
		courses.save!
		end
	end
end

app/models/facility.rb
class Facility < ActiveRecord::Base
	has_many :courses

	def self.import(file)
	CSV.foreach(file.path, headers: true) do |row|
		facilities = find_by_id(row["id"]) ||new
		facilities.attributes = row.to_hash.slice(*Facility.attribute_names())
		facilities.save!
		end
	end	
end

app/models/hole.rb
class Hole < ActiveRecord::Base
	belongs_to :course
	has_many :roundholes

	def self.import(file)
	CSV.foreach(file.path, headers: true) do |row|
		holes = find_by_id(row["id"]) ||new
		holes.attributes = row.to_hash.slice(*Hole.attribute_names())
		holes.save!
		end
	end	
end

app/models/player.rb
class Player < ActiveRecord::Base
	has_many :rounds
	has_many :clubs

	def self.import(file)
	CSV.foreach(file.path, headers: true) do |row|
		players = find_by_id(row["id"]) ||new
		players.attributes = row.to_hash.slice(*Player.attribute_names())
		players.save!
		end
	end	
end

app/models/round.rb
class Round < ActiveRecord::Base
	belongs_to :tee
	belongs_to :player
	belongs_to :course
	has_many :roundholes

	def self.import(file)
	CSV.foreach(file.path, headers: true) do |row|
		rounds = find_by_id(row["id"]) ||new
		rounds.attributes = row.to_hash.slice(*Round.attribute_names())
		rounds.save!
		end
	end	
end

app/models/round_hole.rb
class RoundHole < ActiveRecord::Base
	has_many :shots
	belongs_to :round 
	belongs_to :hole 

	def self.import(file)
	CSV.foreach(file.path, headers: true) do |row|
		roundholes = find_by_id(row["id"]) ||new
		roundholes.attributes = row.to_hash.slice(*RoundHole.attribute_names())
		roundholes.save!
		end
	end	
end

app/models/shot.rb
class Shot < ActiveRecord::Base
	belongs_to :club
	belongs_to :roundhole

	def self.import(file)
	CSV.foreach(file.path, headers: true) do |row|
		shots = find_by_id(row["id"]) ||new
		shots.attributes = row.to_hash.slice(*Shot.attribute_names())
		shots.save!
		end
	end	
end

app/models/tee.rb
class Tee < ActiveRecord::Base
	belongs_to :course
	has_many :rounds

	def self.import(file)
	CSV.foreach(file.path, headers: true) do |row|
		tees = find_by_id(row["id"]) ||new
		tees.attributes = row.to_hash.slice(*Tee.attribute_names())
		tees.save!
		end
	end	
end

app/controllers/holes_controller.rb
class HolesController < ApplicationController
  before_action :set_hole, only: [:show, :edit, :update, :destroy]
  protect_from_forgery with: :null_session #fixed "Can't verify CSRF token authenticity error, however not sure if this opens up security hole"
  respond_to :html, :json, :csv

  # GET /holes
  # GET /holes.json
  def index
    @holes = Hole.all
    respond_with @holes
  end

  # GET /holes/1
  # GET /holes/1.json
  def show
    @hole = Hole.find(params[:id])
    respond_with  @hole
  end

  # GET /holes/new
  def new
    @hole = Hole.new
  end

  # GET /holes/1/edit
  def edit
    @hole = Hole.find(params[:id])
  end

  # POST /holes
  # POST /holes.json
  def create
    @hole = Hole.new(hole_params)
    @hole.save
    respond_with @hole  
  end

  # PATCH/PUT /holes/1
  # PATCH/PUT /holes/1.json
  def update
    @hole = Hole.find(params[:id])
    @hole.update_attributes(hole_params)
    respond_with @hole
  end

  # DELETE /holes/1
  # DELETE /holes/1.json
  def destroy
    @hole = Hole.find(params[:id])
    @hole.destroy
    respond_with @hole
  end

  #Import CSV
  def import
    Hole.import(params[:file])
    redirect_to root_url, alert: "Holes Imported"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hole
      @hole = Hole.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hole_params
      params.require(:hole).permit(:course_id, :number, :par, :handicap)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/tees_controller.rb
class TeesController < ApplicationController
  before_action :set_tee, only: [:show, :edit, :update, :destroy]
  protect_from_forgery with: :null_session #fixed "Can't verify CSRF token authenticity error, however not sure if this opens up security hole"
  respond_to :html, :json, :csv

  # GET /tees
  # GET /tees.json
  def index
    @tees = Tee.all
    respond_with @tees
  end

  # GET /tees/1
  # GET /tees/1.json
  def show
    @tee = Tee.find(params[:id])
    respond_with @tee
  end

  # GET /tees/new
  def new
    @tee = Tee.new
  end

  # GET /tees/1/edit
  def edit
    @tee = Tee.find(params[:id])
  end

  # POST /tees
  # POST /tees.json
  def create
    @tee = Tee.new(tee_params)
    @tee.save
    respond_with @tee
  end

  # PATCH/PUT /tees/1
  # PATCH/PUT /tees/1.json
  def update
    @tee = Tee.find(params[:id])
    @tee.update_attributes(tee_params)
    respond_with @tee
  end

  # DELETE /tees/1
  # DELETE /tees/1.json
  def destroy
    @tee = Tee.find(params[:id])
    @tee.destroy
    respond_with @tee
  end

  #Import CSV
  def import
    Tee.import(params[:file])
    redirect_to root_url, alert: "Tees Imported"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tee
      @tee = Tee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tee_params
      params.require(:tee).permit(:course_id, :name, :distance, :courseRating, :slopeRating)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/facilities_helper.rb
module FacilitiesHelper
end

app/helpers/holes_helper.rb
module HolesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/round_holes_helper.rb
module RoundHolesHelper
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/helpers/shots_helper.rb
module ShotsHelper
end

app/helpers/tees_helper.rb
module TeesHelper
end

app/views/holes/_form.html.erb
<%= form_for(@hole) do |f| %>
  <% if @hole.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hole.errors.count, "error") %> prohibited this hole from being saved:</h2>

      <ul>
      <% @hole.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class="field">
    <%= f.label :course_id%><br>
    <%= f.number_field :course_id%>
  </div>
  <div class="field">
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :par %><br>
    <%= f.number_field :par %>
  </div>
  <div class="field">
    <%= f.label :handicap %><br>
    <%= f.number_field :handicap %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/holes/edit.html.erb
<h1>Editing Hole</h1>

<%= render 'form' %>

<%= link_to 'Show', @hole %> |
<%= link_to 'Back', holes_path %>

app/views/holes/index.csv.erb
<%=
response.content_type = 'application/holes'
CSV.generate do |csv|
	csv << ["id", "course_id", "number", "par", "handicap"]
	@holes.each do |hole|
    csv << [ hole[:id], hole[:course_id], hole[:number], hole[:par], hole[:handicap]]
  end
end .html_safe
%>

app/views/holes/index.html.erb
<div class="container">
<h1>All Holes</h1>

<table class="table table-hover table-responsive table-bordered">
  <thead>
    <tr>
      <th>ID</th>
      <th>Course ID</th>
      <th>Number</th>
      <th>Par</th>
      <th>Handicap</th>
    </tr>
  </thead>

  <tbody>
    <% @holes.each do |hole| %>
      <tr>
        <td><%= hole.id %></td>
        <td><%= hole.course_id %></td>
        <td><%= hole.number %></td>
        <td><%= hole.par %></td>
        <td><%= hole.handicap %></td>
        <td><%= link_to 'Show', hole %></td>
        <td><%= link_to 'Edit', edit_hole_path(hole) %></td>
        <td><%= link_to 'Destroy', hole, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hole', new_hole_path, :class=>"btn btn-primary" %>
<%= link_to '.CSV', holes_path(format: "csv") , :class=>"btn btn-primary" %>

<h2>Import Holes</h2>
<%= form_tag import_holes_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>
</div>

app/views/holes/new.html.erb
<h1>New Hole</h1>

<%= render 'form' %>

<%= link_to 'Back', holes_path %>

app/views/holes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>ID:</strong>
  <%= @hole.id %>
</p>

<p>
  <strong>Course ID:</strong>
  <%= @hole.course_id %>
</p>

<p>
  <strong>Number:</strong>
  <%= @hole.number %>
</p>

<p>
  <strong>Par:</strong>
  <%= @hole.par %>
</p>

<p>
  <strong>Handicap:</strong>
  <%= @hole.handicap %>
</p>

<%= link_to 'Edit', edit_hole_path(@hole) %> |
<%= link_to 'Back', holes_path %>